spring:
  application:
    name: turbine

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

turbine:
  clusterNameExpression: new String("default")
  appConfig: HYSTRIX-EXAMPLE-SERVICE,ENTITYSERVICES-NONCORE,CUSTOMER-CLIENT-SERVICE,EMPLOYEE-PRODUCER,CONSUMER-SERVICE
  combineHostPort: true