server:
  port: 8761
  
#spring:
#  profiles.active: peer1
#   
#eureka:
#  instance:
#    hostname: sjc04d1bemap11
#  client:
#    serviceUrl:
#      defaultZone: http://sjc04d1bemap12:8761/eureka/
      