#spring.cloud.config.server.git.uri= https://github.com/kennyk65/Microservices-With-Spring-Student-Files
#spring.cloud.config.server.git.searchPaths= ConfigData
#server.port=8001

#spring.cloud.config.server.git.uri= https://stash.teslamotors.com/scm/ia/data.quality.services.git

server:
  port: 8001